### ISSUE TITLE
Changes that happen during triggered action not picked up

### ISSUE THREAD

**Issue by francisdb** [swoval/MacOSXWatchService#11]
snapshot you provided + `sbt 1.0.4`
Reproducer on rather large codebase

1. `~test:compile` on root project
2. add `def foo: Unit` to some widely used trait
3. while compilation happens remove the def again and save

You will see that sbt did not pick up the second change, build still shows compilation failed even if the files on disk do not have errors.

Tried this with plain `sbt 1.0.2` without the watch plugin and there it seems to always pick up changes.

**Comment by eatkins** [comment]
Ok. I have a repro for this as well.

**Comment by eatkins** [comment]
Should hopefully be fixed in 1.1.1.

**Comment by francisdb** [comment]
👍🏻 thanks
