### ISSUE TITLE
ignore generated files

### ISSUE THREAD

**Issue by francisdb** [swoval/MacOSXWatchService#19]
This was fixed in sbt 1.0.3 but I am hitting it with this plugin enabled
https://github.com/sbt/sbt-buildinfo/issues/106

workaround of adding `excludeFilter in Compile := "BuildInfo.scala"` fixes it

**Comment by eatkins** [comment]
Would you mind trying again with v1.1.5?

I made some pretty large changes between 1.1.4 and 1.1.5 and you'll have to add `resolvers += Resolver.bintrayIvyRepo("swoval", "sbt-plugins")` until I get the project on maven central. In addition to hopefully resolving this issue, I think that the watch performance should be significantly better on large projects (i.e. shorter delays before the build is triggered after changes).

**Comment by francisdb** [comment]
I can's run sbt on my project any more with the plugin enabled. It seems to no logner load ./project/Dependencies.scala

```
/Users/me/workspace/project/build.sbt:1: error: not found: object Dependencies
import Dependencies._
       ^
```

**Comment by eatkins** [comment]
Yikes. Good catch! I hadn't tested the new version of the plugin when adding the plugin to the global list. It should be fixed now in v1.1.6 (and I fixed a few other issues that I found).

**Comment by francisdb** [comment]
no luck:

```
root(master)> ~test:compile
[error] java.lang.IllegalArgumentException: requirement failed: A named attribute key must start with a lowercase letter: Internal watch state
[error] 	at scala.Predef$.require(Predef.scala:277)
[error] 	at sbt.internal.util.AttributeKey$$anon$1.<init>(Attributes.scala:102)
[error] 	at sbt.internal.util.AttributeKey$.make(Attributes.scala:98)
[error] 	at sbt.internal.util.AttributeKey$.apply(Attributes.scala:65)
[error] 	at com.swoval.watchservice.Continuously$._watchState$lzycompute(Continuously.scala:18)
[error] 	at com.swoval.watchservice.Continuously$._watchState(Continuously.scala:18)
[error] 	at com.swoval.watchservice.Continuously$.executeContinuously(Continuously.scala:45)
[error] 	at com.swoval.watchservice.Continuously$.$anonfun$continuous$2(Continuously.scala:69)
[error] 	at sbt.CommandUtil$.withAttribute(CommandUtil.scala:49)
[error] 	at com.swoval.watchservice.Continuously$.$anonfun$continuous$1(Continuously.scala:66)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:134)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:130)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:153)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:136)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:242)
[error] 	at sbt.State$$anon$1.process(State.scala:248)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:136)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:136)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:129)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:107)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:101)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:57)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:42)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:34)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:113)
[error] 	at sbt.xMain.run(Main.scala:76)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:109)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:117)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:18)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:17)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
```

**Comment by eatkins** [comment]
Yeah, they added that requirement in 1.1.0 (against which I hadn't tested). I will modify the attribute name to fix.

**Comment by eatkins** [comment]
1.1.7 works for me running High Sierra and sbt 1.1.0-RC2. (I previously was testing on 1.0.4.)

**Comment by francisdb** [comment]
More weirdness going on now.

a whole bunch of these
```
PathBinders.scala:6:8: PathBinders is already defined as object PathBinders
[error] object PathBinders {
[error]        ^
```

even when only doing `compile` without `~`
removing the plugin fixes this

**Comment by francisdb** [comment]
on the other hand I have the impression that `1.1.4` with `1.1.0-RC2` + BuildInfo no longer has the repeated compilation problem

**Comment by eatkins** [comment]
Sigh. I suspect that this was due to a similar issue with recursive traversal of the project base directory for source files. Should be fixed in 1.1.8-adf68145ea07785a7a550f0a280afb871f0edbcd. If you still have problems, can you try setting:
`fileCache := com.swoval.watchservice.files.FileCache.NoCache` in `~/.sbt/1.0/global.sbt`?

**Comment by francisdb** [comment]
Still have the `already defined problems`
even with the fileCache setting

I wonder if this is related to some other plugins in my build as without your plugin I also have this which nobody else seems to be having
https://github.com/sbt/sbt/issues/3820

**Comment by francisdb** [comment]
Closing this ticket and creating new one for the "is already defined as"
