### ISSUE TITLE
1.1.5+ breaks unmanaged dependencies

### ISSUE THREAD

**Issue by fsvehla** [swoval/MacOSXWatchService#33]
When using unmanaged dependencies in `lib`, compilation - even when not using triggers - fails when using this plugin.
The observed error message is:

Test with SBT 1.0.4 and 1.1.0

1.1.4: No issue
1.1.5: Definitions in `project/*.scala` not found in SBT
1.1.6: 1.1.5 problem fixed, but:

```
[error] redacted.scala:7:12: object bouncycastle is not a member of package org
[error] import org.bouncycastle.jce.provider.BouncyCastleProvider
```

1.1.7, 1.1.8: identical issue

**Comment by eatkins** [comment]
Yep. Thanks for the report. I believe this should be fixed in 1.2.0-RC1.

**Comment by fsvehla** [comment]
👍 let me know if you need me to test again with branch you are working on

**Comment by eatkins** [comment]
@fsvehla just to be clear, did 1.2.0-RC1 fix your issue?

**Comment by fsvehla** [comment]
@eatkins It does

**Comment by eatkins** [comment]
Great. Thanks!
